//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absences
    {
        public int AbsenceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Days { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsRespectful { get; set; }
        public string DocumentProof { get; set; }
        public string Notes { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
