//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPerformance
    {
        public int PerformanceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Semester { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Grade { get; set; }
        public string GradeType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Teacher { get; set; }
        public string Notes { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
