//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievements
    {
        public int AchievementID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> AchievementTypeID { get; set; }
        public string AchievementName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Level { get; set; }
        public string Place { get; set; }
        public string Document { get; set; }
        public string Notes { get; set; }
    
        public virtual AchievementTypes AchievementTypes { get; set; }
        public virtual Students Students { get; set; }
    }
}
