//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public Nullable<bool> IsLate { get; set; }
        public Nullable<bool> IsAbsentRespectful { get; set; }
        public Nullable<bool> IsAbsentDisrespectful { get; set; }
        public Nullable<int> Hours { get; set; }
        public string Reason { get; set; }
        public Nullable<int> MarkedBy { get; set; }
    
        public virtual Curators Curators { get; set; }
        public virtual Students Students { get; set; }
    }
}
