//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorHours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuratorHours()
        {
            this.CuratorHourAttendance = new HashSet<CuratorHourAttendance>();
        }
    
        public int HourID { get; set; }
        public Nullable<int> CuratorID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public System.DateTime Date { get; set; }
        public string Topic { get; set; }
        public Nullable<int> PresentCount { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuratorHourAttendance> CuratorHourAttendance { get; set; }
        public virtual Curators Curators { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
