//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorHourAttendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> HourID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public string Notes { get; set; }
    
        public virtual CuratorHours CuratorHours { get; set; }
        public virtual Students Students { get; set; }
    }
}
