//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplinaryRecords
    {
        public int RecordID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string RecordType { get; set; }
        public System.DateTime Date { get; set; }
        public string Reason { get; set; }
        public string IssuedBy { get; set; }
        public string Notes { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
