//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.EventParticipation = new HashSet<EventParticipation>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public string Location { get; set; }
        public string Organizer { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventParticipation> EventParticipation { get; set; }
        public virtual EventTypes EventTypes { get; set; }
    }
}
