//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventParticipation
    {
        public int ParticipationID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string ParticipationStatus { get; set; }
        public string Role { get; set; }
        public string Result { get; set; }
        public string Notes { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Students Students { get; set; }
    }
}
