//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParents
    {
        public int StudentParentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsPrimaryContact { get; set; }
    
        public virtual Parents Parents { get; set; }
        public virtual Students Students { get; set; }
    }
}
