//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Absences = new HashSet<Absences>();
            this.AcademicPerformance = new HashSet<AcademicPerformance>();
            this.Achievements = new HashSet<Achievements>();
            this.Attendance = new HashSet<Attendance>();
            this.CuratorHourAttendance = new HashSet<CuratorHourAttendance>();
            this.DisciplinaryRecords = new HashSet<DisciplinaryRecords>();
            this.EventParticipation = new HashSet<EventParticipation>();
            this.StudentParents = new HashSet<StudentParents>();
            this.StudentTraits = new HashSet<StudentTraits>();
            this.StudentCharacteristics = new HashSet<StudentCharacteristics>();
        }
    
        public int StudentID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string StudentCardNumber { get; set; }
        public string PersonalNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Citizenship { get; set; }
        public string EducationBefore { get; set; }
        public string EducationDocument { get; set; }
        public string PhotoPath { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ParentsPhone { get; set; }
        public string RegistrationAddress { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<int> HealthStatusID { get; set; }
        public Nullable<int> FamilyTypeID { get; set; }
        public Nullable<bool> IsOrphan { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> IsFromLargeFamily { get; set; }
        public Nullable<bool> IsLowIncome { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
        public string WorkPlace { get; set; }
        public string WorkPosition { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absences> Absences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicPerformance> AcademicPerformance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achievements> Achievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuratorHourAttendance> CuratorHourAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisciplinaryRecords> DisciplinaryRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventParticipation> EventParticipation { get; set; }
        public virtual FamilyTypes FamilyTypes { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual HealthStatus HealthStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentParents> StudentParents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTraits> StudentTraits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCharacteristics> StudentCharacteristics { get; set; }
    }
}
