//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTraits
    {
        public int TraitID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PositiveTraitID { get; set; }
        public Nullable<int> NegativeTraitID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MarkedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Curators Curators { get; set; }
        public virtual NegativeTraits NegativeTraits { get; set; }
        public virtual PositiveTraits PositiveTraits { get; set; }
        public virtual Students Students { get; set; }
    }
}
